# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ead958f824afa6377b5deeb0e0a98b5555d107eb7796f6f173be4e029032d972adae6888f0c38b881ae4d5f6eaa24458194ecf2e8e2280b503023570913ea7b

test:
  secret_key_base: 87335f6794bff768cbcf649aac05842c758e3155ed747611571c499789088a84074605bd0040d62ed1e57dd7648fd38c770de69b1dfc9df887a0255a23ea9983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
